### ISSUE TITLE
Fatel error detected - Failed to execute script RunOneLauncher

### ISSUE THREAD

**Issue by Technical-13** [JeremyStepp/OneLauncher#5]
![image](https://user-images.githubusercontent.com/4294498/84973325-d629f380-b0ee-11ea-8007-2ac03f3b0fb0.png)

```
2020-06-17 23:01:23,615 - MainWindow - INFO - 647 - Logging started
2020-06-17 23:01:23,615 - MainWindow - INFO - 648 - OneLauncher: 1.2 Dev
2020-06-17 23:01:23,616 - MainWindow - INFO - 649 - Windows-7-6.1.7601-SP1
2020-06-17 23:01:23,619 - OneLauncherUtils - INFO - 70 - SSL certificate verification enabled!
2020-06-17 23:01:23,620 - MainWindow - INFO - 939 - Initializing, please wait...
2020-06-17 23:01:23,620 - MainWindow - CRITICAL - 701 - Uncaught exception:
Traceback (most recent call last):
  File "RunOneLauncher", line 33, in <module>
  File "OneLauncher\Runner.py", line 33, in main
  File "OneLauncher\MainWindow.py", line 178, in __init__
  File "OneLauncher\MainWindow.py", line 772, in InitialSetup
IndexError: list index out of range
2020-06-17 23:01:23,655 - MainWindow - DEBUG - 708 - PySide2.QtCore.QEvent.Type.ZeroTimerEvent : QWindowsGuiEventDispatcher
2020-06-17 23:01:23,655 - MainWindow - DEBUG - 708 - PySide2.QtCore.QEvent.Type.ZeroTimerEvent : QWindowsGuiEventDispatcher
2020-06-17 23:01:23,656 - MainWindow - DEBUG - 708 - PySide2.QtCore.QEvent.Type.ZeroTimerEvent : QWindowsGuiEventDispatcher
```

**Comment by Technical-13** [comment]
Nuking the:
```xml
<DDO.Test>
<HiRes>False</HiRes>
<x64Client>False</x64Client>
<Game.Directory></Game.Directory>
<PatchClient>patchclient.dll</PatchClient>
<Language>EN</Language>
<Accounts/>
</DDO.Test>
```

Section of my OneLauncher.config cleared the error.

**Comment by JeremyStepp** [comment]
Should be fixed.
