### ISSUE TITLE
Client hangs after authentication.

### ISSUE THREAD

**Issue by Technical-13** [JeremyStepp/OneLauncher#6]
```
2020-06-17 23:25:21,450 - MainWindow - INFO - 939 - Account authenticated
2020-06-17 23:25:21,451 - MainWindow - CRITICAL - 701 - Uncaught exception:
Traceback (most recent call last):
  File "OneLauncher\MainWindow.py", line 367, in btnLoginClicked
  File "OneLauncher\MainWindow.py", line 472, in AuthAccount
  File "site-packages\keyring\core.py", line 68, in delete_password
  File "site-packages\keyring\backends\fail.py", line 25, in get_password
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```

**Comment by Technical-13** [comment]
"Hanging" looks like this...
![image](https://user-images.githubusercontent.com/4294498/84975024-6d447a80-b0f2-11ea-8de7-f9021b2b431e.png)

...and the client never opens.

**Comment by JeremyStepp** [comment]
See if it is fixed with [this](https://send.firefox.com/download/5c1e6050cfc8e49e/#PHw82b-wuitHkpvaCYKM6Q) build.
